### ISSUE TITLE
[BUG] bitrate not restoring after arm change

### ISSUE THREAD

**Issue by forcegk** [xveiga/beekeeler#1]
![image](https://user-images.githubusercontent.com/12428595/133820604-2fd0b1ae-bf8a-4059-b721-adea60199521.png)

**Comment by forcegk** [comment]
I'd be easy to solve by disarming before an arm command is processed

**Comment by xveiga** [comment]
Solved on 105f1f14014daa621ec222290d3a6b4fa3d868ad, as you mentioned, by enforcing disarm before rearming. Pending further testing.
